name: Build Android APK Auto Version

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Setup Node.js Environment
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    # Langkah tambahan untuk menyetujui semua lisensi Android SDK otomatis
    - name: Accept Android Licenses
      run: yes | sdkmanager --licenses || true

    - name: Install Cordova
      run: npm install -g cordova

    - name: Create Cordova Project
      run: |
        cordova create output_app com.belajar.musicplayer MusicPlayer
        rm -rf output_app/www output_app/config.xml
        cp -r www output_app/
        cp config.xml output_app/

    # Di sini kita lepas versi android-nya agar otomatis menyesuaikan sistem terbaru
    - name: Build Android Platform
      run: |
        cd output_app
        cordova platform add android --no-telemetry
        cordova build android --device --no-telemetry

    - name: Upload APK Result
      uses: actions/upload-artifact@v4
      with:
        name: BlueHourPlayer-APK
        path: output_app/platforms/android/app/build/outputs/apk/debug/app-debug.apk
